# Generated by Django 3.2.6 on 2021-08-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190330_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='for_all',
            field=models.BooleanField(default=False, verbose_name='for all'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, upload_to='service/icon', verbose_name='icon'),
        ),
    ]
