services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app/src
      - ./media:/app/media
    ports:
     - "8050:8000"
    command: ./manage.py runserver 0.0.0.0:8000
