# Generated by Django 2.1.7 on 2019-03-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_servicegroup_serviceuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicegroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='servicegroup',
            name='service',
        ),
        migrations.RemoveField(
            model_name='serviceuser',
            name='service',
        ),
        migrations.RemoveField(
            model_name='serviceuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceGroup',
        ),
        migrations.DeleteModel(
            name='ServiceUser',
        ),
    ]
