# Generated by Django 2.1.7 on 2019-04-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssh_keys', '0003_auto_20190401_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshkey',
            name='last_seen_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='last seen at'),
        ),
    ]
