# Generated by Django 2.1.7 on 2019-04-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssh_keys', '0004_sshkey_last_seen_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sshkey',
            unique_together={('algorithm', 'bit_length', 'md5_hash')},
        ),
    ]
