# Generated by Django 2.2.8 on 2020-10-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssh_keys', '0005_auto_20190401_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshkey',
            name='sha256_hash',
            field=models.CharField(default='', editable=False, max_length=128, verbose_name='SHA256 hash'),
            preserve_default=False,
        ),
    ]
