# Generated by Django 3.2.6 on 2021-09-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FtpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(null=True)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('passwd', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
