# Generated by Django 3.2.6 on 2021-09-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ftpuser',
            old_name='passwd',
            new_name='password',
        ),
        migrations.AddField(
            model_name='ftpuser',
            name='password_set_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ftpuser',
            name='last_seen_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
