# Generated by Django 2.2 on 2019-04-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.EmailField(db_index=True, max_length=254, verbose_name='source')),
                ('destination', models.EmailField(max_length=254, verbose_name='destination')),
            ],
            options={
                'verbose_name': 'alias',
                'verbose_name_plural': 'aliases',
                'ordering': ('source', 'destination'),
            },
        ),
    ]
