# Generated by Django 4.2.13 on 2026-08-26 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0003_aliasusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedMailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shared mailbox',
                'verbose_name_plural': 'shared mailboxes',
                'ordering': ('name',),
            },
        ),
    ]
